---
- import_tasks: amzn.yml
  when:
    - ansible_distribution == "Amazon"
    - ansible_service_mgr == "upstart"

- import_tasks: el6.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
